#!/usr/bin/env python3
"""Generate the Florida cycling profiles used for routing.

BRouter's stock profiles encode German/EU road law, under which riding on a
footway is forbidden unless it is signed for bicycles. Concretely, trekking.brf
contains:

    else if vehicle= then ( if highway=footway then false else defaultaccess )

so any `highway=footway` without an explicit `bicycle=` tag is access-denied.
In the Kissimmee area that rules out ~98% of a densely mapped sidewalk network
(8,700+ footways, 3,400+ tagged footway=sidewalk, only ~170 carrying any
bicycle tag), and the router answers by putting the rider on US-192 instead.

Florida law runs the other way: §316.2065(9)-(11) permits riding on sidewalks
unless a local ordinance forbids it, with the rider taking on the rights and
duties of a pedestrian. These profiles encode that, and re-price the fast roads
to match how they actually feel on a bike.

Ways tagged `bicycle=no` stay forbidden, so genuine local bans are respected.

    python3 tools/make_profiles.py        # regenerate from upstream trekking.brf
"""
import pathlib
import sys
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "tools" / "profiles"
UPSTREAM = ("https://raw.githubusercontent.com/abrensch/brouter/master/"
            "misc/profiles2/trekking.brf")

HEADER = """# {name}
#
# Generated by tools/make_profiles.py from BRouter's trekking.brf.
# Do not hand-edit: change the edits in that script and regenerate.
#
# {summary}
"""

# Let bikes onto untagged footways. `bicycle=no` is still refused, because that
# branch is only reached when the way carries no bicycle tag at all.
ALLOW_FOOTWAY = (
    "         else if vehicle= then ( if highway=footway then false else defaultaccess )",
    "         else if vehicle= then defaultaccess"
    "  # FL: sidewalk riding is legal (FS 316.2065)",
)

# A sidewalk is slower than the road and has driveway and pedestrian conflicts,
# so it is not free — it just has to cost less than a 55 mph arterial.
FOOTWAY_COST = (
    "  else if ( highway=service                   ) then ( if isunpaved then 1.6 else 1.3 )",
    "  else if ( highway=service                   ) then ( if isunpaved then 1.6 else 1.3 )\n"
    "\n"
    "  # Sidewalks: usable here, but slower than the carriageway and busy with\n"
    "  # driveways and people on foot, so priced above a quiet street and well\n"
    "  # below anything with fast traffic.\n"
    "  else if ( highway=footway                   ) then ( if isunpaved then {fw_unpaved} else {fw} )",
)


def road_costs(trunk_bike, trunk, primary_bike, primary, secondary_bike, secondary):
    old = (
        "       if ( highway=trunk|trunk_link         ) then ( if isbike then 1.5 else 10  )\n"
        "  else if ( highway=primary|primary_link     ) then ( if isbike then 1.2 else  3  )\n"
        "  else if ( highway=secondary|secondary_link ) then ( if isbike then 1.1 else 1.6 )"
    )
    new = (
        f"       if ( highway=trunk|trunk_link         ) then ( if isbike then {trunk_bike} else {trunk} )\n"
        f"  else if ( highway=primary|primary_link     ) then ( if isbike then {primary_bike} else {primary} )\n"
        f"  else if ( highway=secondary|secondary_link ) then ( if isbike then {secondary_bike} else {secondary} )"
    )
    return old, new


PROFILES = {
    "florida-balanced": {
        "summary": ("Everyday riding. Sidewalks allowed and priced sensibly; "
                    "fast roads cost more than stock trekking, but a genuinely "
                    "direct road with a bike lane can still win."),
        "footway": ("1.45", "2.2"),
        "roads": road_costs("4.0", "15", "1.8", "5", "1.15", "2.2"),
    },
    "florida-calm": {
        "summary": ("Avoid traffic. Sidewalks and paths are strongly preferred "
                    "and high-speed roads are priced near-prohibitively, so the "
                    "route will take a real detour to stay off them."),
        "footway": ("1.15", "1.8"),
        "roads": road_costs("9.0", "30", "3.5", "12", "1.6", "4.0"),
    },
}


def build(base, key, spec):
    text = base
    for old, new in (ALLOW_FOOTWAY, ):
        if old not in text:
            sys.exit(f"upstream profile changed: could not find\n  {old}")
        text = text.replace(old, new, 1)

    old, new = FOOTWAY_COST
    if old not in text:
        sys.exit("upstream profile changed: service-road cost line not found")
    fw, fw_unpaved = spec["footway"]
    text = text.replace(old, new.format(fw=fw, fw_unpaved=fw_unpaved), 1)

    old, new = spec["roads"]
    if old not in text:
        sys.exit("upstream profile changed: trunk/primary/secondary costs not found")
    text = text.replace(old, new, 1)

    return HEADER.format(name=key, summary=spec["summary"]) + text


def main():
    print(f"fetching {UPSTREAM}")
    req = urllib.request.Request(UPSTREAM,
                                 headers={"User-Agent": "PublixBikeCommuter/1.0"})
    with urllib.request.urlopen(req, timeout=60) as fh:
        base = fh.read().decode()

    OUT.mkdir(parents=True, exist_ok=True)
    for key, spec in PROFILES.items():
        path = OUT / f"{key}.brf"
        path.write_text(build(base, key, spec))
        print(f"  wrote {path.relative_to(ROOT)} ({path.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
